"""PNG export derived from SVG rendering."""

from __future__ import annotations

from pathlib import Path
import struct
import zlib

from .errors import RenderError
from .model import TartanSpec
from .render_svg import GENERATOR, render_svg

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    """Build a PNG chunk."""
    crc = zlib.crc32(chunk_type)
    crc = zlib.crc32(data, crc) & 0xFFFFFFFF
    return struct.pack("!I", len(data)) + chunk_type + data + struct.pack("!I", crc)


def _png_text_chunk(keyword: str, text: str) -> bytes:
    """Build a PNG tEXt chunk.

    PNG tEXt chunks are Latin-1. Non-Latin-1 characters are replaced so metadata
    never breaks the generated image.
    """
    keyword_bytes = keyword.encode("latin-1", "replace")
    text_bytes = text.encode("latin-1", "replace")
    return _png_chunk(b"tEXt", keyword_bytes + b"\x00" + text_bytes)


def _add_generator_metadata(png: bytes, spec: TartanSpec) -> bytes:
    """Insert generator comments into a PNG byte stream.

    The SVG remains the canonical rendering. These PNG text chunks simply preserve
    provenance after CairoSVG converts the SVG to raster form.
    """
    if not png.startswith(PNG_SIGNATURE):
        raise RenderError("PNG backend returned data without a valid PNG signature")

    software = _png_text_chunk("Software", GENERATOR)
    description = _png_text_chunk("Description", f"Generated by {GENERATOR} from SVG for {spec.name}")

    # Insert after IHDR, which is the first chunk in every valid PNG.
    offset = len(PNG_SIGNATURE)
    if len(png) < offset + 8:
        raise RenderError("PNG backend returned truncated PNG data")
    ihdr_length = struct.unpack("!I", png[offset : offset + 4])[0]
    ihdr_end = offset + 12 + ihdr_length
    if png[offset + 4 : offset + 8] != b"IHDR" or len(png) < ihdr_end:
        raise RenderError("PNG backend returned malformed PNG data")

    return png[:ihdr_end] + software + description + png[ihdr_end:]


def render_png(
    spec: TartanSpec,
    *,
    output_width: int | None = None,
    output_height: int | None = None,
    scale: float | None = None,
) -> bytes:
    """Render PNG bytes by first generating SVG."""
    try:
        import cairosvg
    except ImportError as exc:
        raise RenderError(
            'PNG export requires the optional dependency cairosvg. Install with: pip install "tartan-maker[png]"'
        ) from exc

    svg = render_svg(spec)
    kwargs: dict[str, object] = {}
    if output_width is not None:
        kwargs["output_width"] = output_width
    if output_height is not None:
        kwargs["output_height"] = output_height
    if scale is not None:
        kwargs["scale"] = scale
    png = cairosvg.svg2png(bytestring=svg.encode("utf-8"), **kwargs)
    return _add_generator_metadata(png, spec)


def write_png(
    spec: TartanSpec,
    path: str | Path,
    *,
    output_width: int | None = None,
    output_height: int | None = None,
    scale: float | None = None,
) -> None:
    """Render PNG from SVG and write it to disk."""
    png = render_png(spec, output_width=output_width, output_height=output_height, scale=scale)
    Path(path).write_bytes(png)
